### Setup sample wildcard:
import os
from glob import glob

SAMPLE = [os.path.basename(fn).replace("_1.fq.gz", "")
            for fn in glob(f"resources/reads/*_1.fq.gz")]

################################################################################
### Setup the desired outputs
rule all:
    input:
        "results/coverm/counts.tsv"

################################################################################
### Filter reads with fastp
rule fastp:
    input:
        r1 = "resources/reads/{sample}_1.fq.gz",
        r2 = "resources/reads/{sample}_2.fq.gz"
    output:
        r1 = temp("results/fastp/{sample}_1.fq.gz"),
        r2 = temp("results/fastp/{sample}_2.fq.gz"),
        fastp_html = "results/fastp/{sample}.html",
        fastp_json = "results/fastp/{sample}.json"
    threads:
        4
    resources:
        mem_mb=lambda wildcards, input, attempt: max(8*1024, int(input.size_mb * 5) * 2 ** (attempt - 1)),
        runtime=lambda wildcards, input, attempt: max(10, int(input.size_mb / 1024 * 10) * 2 ** (attempt - 1))
    message:
        "Using FASTP to trim adapters and low quality sequences for {wildcards.sample}"
    shell:
        """
        module load fastp/0.23.4
        fastp \
            --in1 {input.r1} --in2 {input.r2} \
            --out1 {output.r1} --out2 {output.r2} \
            --trim_poly_g \
            --trim_poly_x \
            --n_base_limit 5 \
            --qualified_quality_phred 20 \
            --length_required 60 \
            --thread {threads} \
            --html {output.fastp_html} \
            --json {output.fastp_json} \
            --adapter_sequence CTGTCTCTTATACACATCT \
            --adapter_sequence_r2 CTGTCTCTTATACACATCT
        """

################################################################################
## Index Unite database:
rule index_unite:
    input:
        "resources/database/sh_general_release_dynamic_s_all_19.02.2025.fasta"
    output:
        touch('resources/database/index.done') # Flag file
    params:
        database = "resources/database/sh_general_release_dynamic_s_all_19.02.2025"
    threads:
        24
    resources:
        mem_mb=lambda wildcards, input, attempt: max(8*1024, int(input.size_mb * 5) * 2 ** (attempt - 1)),
        runtime=lambda wildcards, input, attempt: max(10, int(input.size_mb / 1024 * 5) * 2 ** (attempt - 1))
    message:
        "Indexing unite database with Bowtie2"
    shell:
        """
        module load bowtie2/2.4.2
        # Index MAG gene catalogue
        bowtie2-build \
            --large-index \
            --threads {threads} \
            {input} {params.database}
        """

################################################################################
### Map non-host reads to DRAM genes files using Bowtie2
rule bowtie2_unite_mapping:
    input:
        idx = "resources/database/index.done",
        r1 = "results/fastp/{sample}_1.fq.gz",
        r2 = "results/fastp/{sample}_2.fq.gz",
    output:
        bam = "results/bowtie/{sample}.bam"
    params:
        database = "resources/database/sh_general_release_dynamic_s_all_19.02.2025"
    threads:
        20
    resources:
        mem_mb=lambda wildcards, input, attempt: max(8*1024, int(input.size_mb * 2) * 2 ** (attempt - 1)),
        runtime=lambda wildcards, input, attempt: max(10, int(input.size_mb / 1024 * 5) * 2 ** (attempt - 1))
    message:
        "Mapping {wildcards.sample} to unite using Bowtie2"
    shell:
        """
        # Map reads to MAGs using Bowtie2
        module load bowtie2/2.4.2 samtools/1.21
        bowtie2 \
            --time \
            --threads {threads} \
            -x {params.database} \
            -1 {input.r1} \
            -2 {input.r2} \
            --seed 1337 \
        | samtools sort -@ {threads} -o {output.bam}
        """

################################################################################
### Calculate the number of reads that mapped to MAG catalogue genes with CoverM
rule coverM_counts:
    input:
        expand("results/bowtie/{sample}.bam", sample=SAMPLE)
    output:
        gene_counts = "results/coverm/counts.tsv"
    threads:
        8
    resources:
        mem_mb=lambda wildcards, input, attempt: max(8*1024, int(input.size_mb) * 2 ** (attempt - 1)),
        runtime=lambda wildcards, input, attempt: max(10, int(input.size_mb / 1024 * 2) * 2 ** (attempt - 1))
    message:
        "Calculating MAG gene mapping rate using CoverM"
    shell:
        """
        module load coverm/0.7.0
        coverm contig \
            -b {input} \
            -m count \
            -t {threads} \
            --proper-pairs-only \
            > {output.gene_counts}
        """
